Add check-bgp-summary-netconf.rule
Juniper/healthbot-rules pull request #371
Opened 2020-08-28 12:41 UTC by bmadhavi74

2020-08-29 12:59 UTC, gvarao approved these changes

2020-08-29 12:59 UTC, gvarao commented on community_supplied/Protocols/Bgp/check-bgp-summary-netconf.rule
> +            trigger bgp-neighbor {
change the trigger name to "bgp-neighbor-existence"

2020-08-29 12:59 UTC, gvarao commented on community_supplied/Protocols/Bgp/check-bgp-summary-netconf.rule
> +                            message "Neighbor address ($peer-address) is configured. Neighbor state is Established.";
change from "Neighbor address ($peer-address) is configured. Neighbor state is Established." to
"Neighbor address ($peer-address) is configured. Neighbor state is $peer-state."

2020-08-29 12:59 UTC, gvarao commented on community_supplied/Protocols/Bgp/check-bgp-summary-netconf.rule
> +                            message "Neighbor address ($peer-address) is configured. Neighbor state ($peer-state) is not Established.";
change message to"Neighbor address ($peer-address) is configured. Neighbor state is $peer-state."

2020-08-29 13:01 UTC, gvarao requested changes
please do changes

2020-08-29 14:55 UTC, bmadhavi74 commented
Made the required changes and committed.

2020-08-30 07:53 UTC, gvarao approved these changes

2020-08-30 07:53 UTC, merged