Newbranch24
Juniper/healthbot-rules pull request #442
Opened 2020-10-16 12:26 UTC by vvikramb

Added offset values to triggers.

2020-10-16 16:08 UTC, gvarao requested changes

2020-10-16 16:08 UTC, gvarao commented on juniper_official/Interfaces/check-lacp-state-netconf.rule
> +                frequency 1.11offset;
Make offset to 1.1 instead of 1.11

2020-10-19 03:23 UTC, vvikramb commented on juniper_official/Interfaces/check-lacp-state-netconf.rule
> +                frequency 1.11offset;
Updated to 1.1 offset in the file.

2020-10-20 04:16 UTC, vvikramb commented
jenkins please try a build

2020-10-20 04:17 UTC, vvikramb commented
jenkins please retry a build

2020-10-20 04:20 UTC, gvarao commented
jenkins please retry a build

2020-10-20 08:10 UTC, vvikramb commented
jenkins please retry a build

2020-10-20 11:11 UTC, gvarao approved these changes

2020-10-20 11:11 UTC, merged