Security Compliance
Juniper/healthbot-rules pull request #575
Opened 2021-09-27 08:47 UTC by vvikramb

Security Compliance

2021-09-28 05:42 UTC, gvarao requested changes

2021-09-28 05:42 UTC, gvarao commented on juniper_official/Security-Compliance/check-snmp-server-config.rule
> +             */
Rule deployed but no data is coming

2021-09-28 05:42 UTC, gvarao commented on juniper_official/Security-Compliance/check-ssh-services.rule
> +healthbot {
Rule deployed but no data is coming

2021-09-29 03:52 UTC, vvikramb commented on juniper_official/Security-Compliance/check-community-access.rule
> +                    }
Added SRX in rule properties.

2021-09-29 03:54 UTC, vvikramb commented on juniper_official/Security-Compliance/check-interface-protocols.rule
> +            }
Changed frequency from 60s to 6h.

2021-09-29 03:54 UTC, vvikramb commented on juniper_official/Security-Compliance/check-interface-protocols.rule
> +                    }
Added SRX in rule properties.

2021-09-29 03:59 UTC, vvikramb commented on juniper_official/Security-Compliance/ntpAuthentication.yml
> +---
Updated spaces.

2021-09-29 03:59 UTC, vvikramb commented on juniper_official/Security-Compliance/ntpServers.yml
> +---
Updated spaces.

2021-09-29 04:00 UTC, vvikramb commented on juniper_official/Security-Compliance/check-community-access.rule
> +                    frequency 60s;
Update frequency from 60s to 6h.

2021-09-29 04:01 UTC, vvikramb commented on juniper_official/Security-Compliance/check-community-access.rule
> +             * Fields defined with variables and constant values
Updated comments for fields.

2021-09-29 04:01 UTC, vvikramb commented on juniper_official/Security-Compliance/check-community-access.rule
> +                            message "Community $communityname is applied to client list $communityListName and has read only permission.";
Removed community name in message.

2021-09-29 04:02 UTC, vvikramb commented on juniper_official/Security-Compliance/check-community-access.rule
> +                            message "Community $communityname is applied to client list $communityListName and  has read-write permission.";
Removed community name in message.

2021-09-29 04:02 UTC, vvikramb commented on juniper_official/Security-Compliance/check-interface-protocols.rule
> +                    frequency 60s;
Changed frequency from 60s to 6h.

2021-09-29 04:04 UTC, vvikramb commented on juniper_official/Security-Compliance/check-interface-protocols.rule
> +                            message "isis interface all should not be set.";
Checking if "interface all" is enabled for isis protocols and raising alarm if it is set.

2021-09-29 04:05 UTC, vvikramb commented on juniper_official/Security-Compliance/check-interface-protocols.rule
> +                            message "lldp interface all should not be set.";
Checking if "interface all" is enabled for lldp protocols and raising alarm if it is set.

2021-09-29 04:06 UTC, vvikramb commented on juniper_official/Security-Compliance/check-interface-protocols.rule
> +                            message "source-packet-routing should not be enabled.";
Checking if "source packet routing is enabled" and raising red alarm if it is set.

2021-09-29 04:06 UTC, vvikramb commented on juniper_official/Security-Compliance/check-community-access.rule
> +                description "authorization type.";
Removed full stop from all descriptions.

2021-09-29 04:07 UTC, vvikramb commented on juniper_official/Security-Compliance/check-interface-to-disable.rule
> +/*
Made the changes for all rules.

2021-09-29 04:08 UTC, vvikramb commented on juniper_official/Security-Compliance/check-interface-to-disable.rule
> +                            message "The list of interfaces that do not have configuration and can be diabled.$list-of-interfaces-make-down";
Updated to match only ethernet interfaces.

2021-09-29 04:09 UTC, vvikramb commented on juniper_official/Security-Compliance/check-interface-protocols.rule
> +                            message "ospf interface all should not be set.";
Checking if "interface all" is enabled for ospf protocols and raising alarm if it is set.

2021-09-29 04:11 UTC, gvarao approved these changes

2021-09-29 04:11 UTC, merged