RCA resource files
Juniper/healthbot-rules pull request #589
Opened 2021-11-19 16:59 UTC by gvarao

2021-11-21 01:46 UTC, gvarao commented
jenkins please retry a build

2021-11-21 07:10 UTC, gvarao commented
jenkins please retry a build

2021-11-22 03:55 UTC, gvarao commented
jenkins please retry a build

2021-11-22 04:06 UTC, sharanyabhat commented
jenkins please retry a build

2021-11-22 04:07 UTC, gvarao commented
jenkins please retry a build

2021-11-22 04:33 UTC, gvarao commented
jenkins please retry a build

2021-11-26 05:57 UTC, gaddevijay requested changes

2021-11-26 06:57 UTC, gvarao commented on juniper_official/Chassis/chassis.resource
> +        resource chassis-temperature {
Chassis-temperature depended on fan failure hence not other way around. 
Agree with you and I have add depends-on-multiple-instances true;

2021-11-26 06:59 UTC, gvarao commented on juniper_official/Chassis/chassis.resource
> +        resource re-temperature {
Agree and modified to routing-engine

2021-11-26 07:02 UTC, gvarao commented on juniper_official/Interfaces/check-ifl-status.rule
> +                        matches-with "$ifl-admin-status" DOWN {
Initially i wanted to ignore admin down IFLs. But thought about and removed term now as it is not proper use case

2021-11-26 07:04 UTC, gvarao commented on juniper_official/Protocols/Isis/isis.resource
> +                term ifl-dependency {
We can form but it is not straight forward. I will try to add in next release

2021-11-26 07:09 UTC, gvarao commented on juniper_official/Protocols/Mpls/mpls.resource
> +                term rsvp-neighbor-dependency {
Yes we can have only one rsvp neighbor.

2021-11-26 07:14 UTC, gvarao commented on juniper_official/Protocols/Ospf/ospf.resource
> +        			}
Corrected

2021-11-26 07:16 UTC, gvarao commented on juniper_official/System/system.resource
> +            depends-on system/system-storage {
We have verified again with rama and he suggested.

2021-11-26 08:18 UTC, gvarao commented on juniper_official/Protocols/Ospf/ospf.resource
> +                        	field-name "$remote-ospf:interface-name";
Modified as we discussed

2021-11-26 08:18 UTC, gvarao commented on juniper_official/System/system.resource
> +            depends-on system/system-storage {
Modified as we discussed

2021-11-26 08:18 UTC, gvarao commented on juniper_official/System/system.resource
> +            depends-on system/system-memory {
Modified as we discussed

2021-11-30 05:14 UTC, gaddevijay commented on juniper_official/Protocols/Ospf/ospf.resource
> +                    rule protocol.ospf/check-ospf-neighbor-information {
Checked with Venkat. Seems like there is only one rule

2021-11-30 05:17 UTC, gaddevijay commented on juniper_official/Protocols/Ospf/ospf.resource
> +                        	field-name "$remote-ospf:interface-name";
This is not modified. Backend support is required

2021-11-30 05:21 UTC, gaddevijay approved these changes

2021-11-30 05:21 UTC, merged