Consolidate july11
Juniper/healthbot-rules pull request #637
Opened 2022-07-11 10:08 UTC by vvikramb

Add rules.

2022-07-16 07:51 UTC, gaddevijay requested changes

2022-07-16 07:51 UTC, gaddevijay commented on juniper_official/Consolidated_Rules/check-system-power-usage-temp-state.rule
> +            trigger Chassis-temperature {
small cause

2022-07-22 04:50 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-fpc-cpu-memory-state-temp.rule
> +            synopsis "FPC memory analyzer";
Replaced "linecard" with "fpc" incuding the topic name.

2022-07-22 04:53 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-fpc-cpu-memory-state-temp.rule
> +             * Use FPC name as key for rule.
replaced "linecard" to "fpc".

2022-07-22 06:35 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-fpc-cpu-memory-state-temp.rule
> +                            time-range 6offset;
We want to raise the alarm only when utilization is seen to be increasing continously.Else any spike would raise an alarm if threshold is breached.
Should we remove/reduce the offset value?

2022-07-22 07:30 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-optical-signal-loss-fec-rx-power.rule
> +                synopsis "Interface optics iAgent sensor definition";
corrected

2022-07-22 07:31 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-optical-signal-loss-fec-rx-power.rule
> +                    sensor-name /junos/system/linecard/optics/;
yes

2022-07-22 10:47 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-psm-power-usage-state-temp.rule
> +                    where "/components/component/properties/property/@name == 'state'";
Deleted the extra clause.

2022-07-22 10:50 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-psm-power-usage-state-temp.rule
> +                    sensor-name /components/component;
Changed sensor path to /components/ and frequency to 60s in the rules.

2022-07-22 10:53 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-psm-power-usage-state-temp.rule
> +                            message "$psm is not online.";
Updated psm state in the message.

2022-07-22 10:58 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-psm-power-usage-state-temp.rule
> +            trigger system-power-usage {
it is system power usage.

2022-07-22 11:02 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-system-cpu-memory-temp.rule
> +             trigger re-cpu-utilization {
Changed to routing engine.

2022-07-22 11:04 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-system-cpu-memory-temp.rule
> +                             time-range 5offset;
Have changed it to 2offset.

2022-07-22 11:17 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-optical-signal-loss-fec-rx-power.rule
> +            trigger fec-uncorrected {
Updated to "uncorrected-forward-error-correction-errors".

2022-07-22 12:14 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-optical-signal-loss-fec-rx-power.rule
> +                    path "/interfaces/interface/@name";
admin state sensor is not available under the sensor path.

2022-07-22 14:27 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-optical-temp-thresholds.rule
> +                    where "/interfaces/interface/@name =~ /{{if-name}}/";
Updated where condition and checked, data is not showing with where condition, need to debug.

2022-07-25 08:33 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-pfe-discards.rule
> +                            message "Increasing data-error-discard count $data-error-discard";
Planning to add field that uses "rate of change" formula.

2022-07-26 06:05 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-interface-in-out-errors-traffic-state-flaps.rule
> +                    where "/interfaces/interface/@name =~ /{{interface-name-variable}}/";
Filtering out the down interfaces in the interface field.

2022-07-28 03:19 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-fpc-cpu-memory-state-temp.rule
> +                            time-range 6offset;
Changed it to 3offset.

2022-07-28 03:37 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-optical-signal-loss-fec-rx-power.rule
> +                    frequency 60s;
Changed to 60s for all rules.

2022-07-28 03:45 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-optical-signal-loss-fec-rx-power.rule
> +                            time-range 2880offset;
It was a typo, changed to 2offset.

2022-07-28 03:46 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-optical-signal-loss-fec-rx-power.rule
> +                            time-range 2880offset;
It was a typo, changed to 2offset.

2022-07-28 03:48 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-optical-temp-thresholds.rule
> +                path optics-threshold-adjustment.py;
The file is in this location : https://github.com/Juniper/healthbot-rules/tree/master/juniper_official/Optical.
I think Eval cannot be used, need to write a pre-defined function.

2022-07-28 03:50 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-pfe-discards.rule
> +                            message "Increasing data-error-discard count $data-error-discard";
Added rate of change.

2022-07-28 03:50 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-pfe-discards.rule
> +                            message "Increasing bad-route-discard drop count $bad-route-discard";
Added rate of change.

2022-07-28 03:50 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-pfe-discards.rule
> +                            message "Increasing fabric drop count $fabric-discard";
Added rate of change.

2022-07-28 03:50 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-pfe-discards.rule
> +                            message "Increasing invalid-iif-discard drop count $invalid-iif-discard";
Added rate of change.

2022-07-28 03:50 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-pfe-discards.rule
> +                            message "Increasing stack-overflow-discard drop count $stack-overflow-discard";
Added rate of change.

2022-07-28 03:52 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-psm-power-usage-state-temp.rule
> +            trigger psm-is-online {
Changed to psm-state

2022-07-28 03:53 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-psm-power-usage-state-temp.rule
> +            trigger system-power-usage {
Changed to "psm-power-usage".

2022-07-28 03:55 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-system-cpu-memory-temp.rule
> +                             time-range 5offset;
Changed to 3offset.

2022-07-28 03:58 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-system-cpu-memory-temp.rule
> +            trigger re-temperature {
Moved to new rule under chassis topic.

2022-07-28 03:58 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-system-cpu-memory-temp.rule
> +            trigger re-cpu-temperature {
Moved to new rule under chassis topic.

2022-07-28 03:59 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-system-power-usage-temp-state.rule
> +                    sensor-name /components/component;
Changed to /components/

2022-08-12 03:23 UTC, gvarao commented on juniper_official/chassis/check-fan-state-rpm.rule
> +            description "Checks Fan state and RPM percentage";
Replace description to "Collects chassis environment statistics periodically and notifies anomalies when fan status is NOK"

2022-08-12 03:27 UTC, gvarao commented on juniper_official/chassis/check-fan-state-rpm.rule
> +                description "Name of the fan tray and fan number.";
Remove period(dots) in the end from all descriptions and synopsis of all rules and playbooks

2022-08-12 03:28 UTC, gvarao commented on juniper_official/chassis/check-fan-state-rpm.rule
> +                description "RPM measurement.";
Same as above

2022-08-12 03:30 UTC, gvarao commented on juniper_official/chassis/check-fan-state-rpm.rule
> +                term state-is-ok {
Add comment and provide details for all term in all rules. E.g.
                /*
                 * Sets color to green when fan status is OK.
                 */

2022-08-12 03:30 UTC, gvarao commented on juniper_official/chassis/check-fan-state-rpm.rule
> +                term state-is-not-ok {
Same as above

2022-08-12 03:31 UTC, gvarao commented on juniper_official/chassis/check-fan-state-rpm.rule
> +            trigger fan-state {
Trigger synopsis and description missing in most of the rules. please add in all rules

2022-08-12 03:31 UTC, gvarao commented on juniper_official/chassis/check-fan-state-rpm.rule
> +                frequency 1offset;
Trigger synopsis and description missing in most of the rules. please add in all rules

2022-08-12 03:32 UTC, gvarao commented on juniper_official/chassis/check-fan-state-rpm.rule
> +                term above-high-threshold {
Add comment for each term

2022-08-12 03:33 UTC, gvarao commented on juniper_official/chassis/check-psm-power-usage-state-temp.rule
> + *
Same comments as above rule

2022-08-12 03:36 UTC, gvarao commented on juniper_official/chassis/fanEVOTable.yml
> +fanEVOTable:
Add "---" in the beginning of file which is recommended and mandatory

2022-08-12 03:37 UTC, gvarao commented on juniper_official/interface/check-interface-in-out-errors-traffic-state-flaps.rule
> + * Monitors interface fields and notifies when anomalies are found.
s/Monitors interface fields/Monitors interface KPIs/g

2022-08-12 03:39 UTC, gvarao commented on juniper_official/interface/check-interface-in-out-errors-traffic-state-flaps.rule
> +                            message "$interface-name output errors count  is normal.";
Remove extra space
s/count  is/count is/g

2022-08-12 03:42 UTC, gvarao commented on juniper_official/interface/check-optical-signal-loss-fec-tx-rx-power.rule
> + * Detects interface optics signal loss,checks for fec uncorrected errors and monitors
Rephrase comment something like Monitor interface optics stats like signal loss, power, and errors and notify anomalies

2022-08-12 03:46 UTC, gvarao commented on juniper_official/interface/check-optical-signal-loss-fec-tx-rx-power.rule
> +                            message "Rx power $optics-rx-power is above alarm threshold $rx-high-alarm-threshold for interface $interface-name lane $lane-index.";
Shorten message something like below

$interface-name, Lane $lane-index Rx power($optics-rx-power) is above alarm threshold($rx-high-alarm-threshold)

2022-08-12 03:46 UTC, gvarao commented on juniper_official/interface/check-optical-signal-loss-fec-tx-rx-power.rule
> +                            message "Rx power $optics-rx-power is above warning threshold $rx-high-warning-threshold for interface $interface-name lane $lane-index.";
same as above

2022-08-12 03:46 UTC, gvarao commented on juniper_official/interface/check-optical-signal-loss-fec-tx-rx-power.rule
> +                            message "Rx power $optics-rx-power is normal for interface $interface-name lane $lane-index.";
Same as above

2022-08-12 03:46 UTC, gvarao commented on juniper_official/interface/check-optical-signal-loss-fec-tx-rx-power.rule
> +                            message "Rx power $optics-rx-power is below warning threshold $rx-low-warning-threshold for interface $interface-name lane $lane-index.";
same as above

2022-08-12 03:47 UTC, gvarao commented on juniper_official/interface/check-optical-signal-loss-fec-tx-rx-power.rule
> +                            message "Tx power $optics-tx-power is above alarm threshold $tx-high-alarm-threshold for interface $interface-name lane $lane-index.";
same as above comment

2022-08-12 03:47 UTC, gvarao commented on juniper_official/interface/check-optical-signal-loss-fec-tx-rx-power.rule
> +                            message "Tx power $optics-tx-power is above warning threshold $tx-high-warning-threshold for interface $interface-name lane $lane-index.";
same as above comment

2022-08-12 03:47 UTC, gvarao commented on juniper_official/interface/check-optical-signal-loss-fec-tx-rx-power.rule
> +                            message "Tx power $optics-tx-power is below alarm threshold $tx-low-alarm-threshold for interface $interface-name lane $lane-index.";
same as above comment

2022-08-12 03:47 UTC, gvarao commented on juniper_official/interface/check-optical-signal-loss-fec-tx-rx-power.rule
> +                            message "Tx power $optics-tx-power is below warning threshold $tx-low-warning-threshold for interface $interface-name lane $lane-index.";
same as above comment

2022-08-12 03:49 UTC, gvarao commented on juniper_official/interface/check-optical-temp-thresholds.rule
> +                    list-of-files optics-threshold-adjustment.py;
Python file missing in commit

2022-08-12 03:50 UTC, gvarao commented on juniper_official/interface/check-optical-temp-thresholds.rule
> +                            message "Temperature of the optical module $interface-name , $optical-temp exceeds default alarm threshold $high-alarm-threshold ";
Shorten message

2022-08-12 03:53 UTC, gvarao commented on juniper_official/system/check-system-cpu-memory.rule
> + *
Variable 5 i.e. memory-buffer-re-low-threshold comment missing

2022-08-13 14:21 UTC, gaddevijay commented on juniper_official/Consolidated_Rules/check-interface-in-out-errors-traffic-state-flaps.rule
> +                            message "In errors are increasing continuously on $interface-name, Error count is:$in-errors-count";
Seems like this is not taken care of

2022-08-13 14:22 UTC, gaddevijay commented on juniper_official/Consolidated_Rules/check-interface-in-out-errors-traffic-state-flaps.rule
> +                            message "Out errors are increasing continuously on $interface-name, Error count is:$out-errors-count";
Not taken care of

2022-08-16 04:36 UTC, vvikramb commented on chassis/check-chassis-alarms.rule
> +	        /*
Fixed.

2022-08-16 04:37 UTC, vvikramb commented on chassis/check-chassis-alarms.rule
> +            sensor chassis {
updated sensor name to chassis-netconf

2022-08-17 04:34 UTC, vvikramb commented
Jenkins please retry a build

2022-08-17 04:44 UTC, vvikramb commented
Jenkins please retry a build

2022-08-18 05:13 UTC, vvikramb commented
Jenkins please retry a build

2022-08-18 12:48 UTC, sharanyab16 commented
Jenkins please retry a build

2022-08-22 12:29 UTC, vvikramb commented
> Go through all rules and address comments.

Updated all comments.

2022-08-22 12:37 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-interface-in-out-errors-traffic-state-flaps.rule
> +                            message "In errors are increasing continuously on $interface-name, Error count is:$in-errors-count";
Updated the messages where it was missing.

2022-08-22 12:37 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-interface-in-out-errors-traffic-state-flaps.rule
> +                            message "In errors are increasing continuously on $interface-name, Error count is:$in-errors-count";
message "Input errors are increasing continuously on $interface-name, Error count is:$in-errors-count";

2022-08-22 12:38 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-interface-in-out-errors-traffic-state-flaps.rule
> +                            message "Out errors are increasing continuously on $interface-name, Error count is:$out-errors-count";
Updated  message "Output errors are increasing continuously on $interface-name, Error count is:$out-errors-count";

2022-08-22 12:44 UTC, vvikramb commented on juniper_official/Consolidated_Rules/check-optical-temp-thresholds.rule
> +                    where "/interfaces/interface/@name =~ /{{if-name}}/";
After discussion with GV, Down interfaces to be taken care of by foghorn, we will be monitoring only UP interfaces.

2022-08-23 08:19 UTC, gaddevijay approved these changes

2022-08-23 08:20 UTC, gvarao approved these changes

2022-08-23 08:20 UTC, merged