RLI - 52835
Juniper/healthbot-rules pull request #643
Opened 2022-07-27 12:26 UTC by sandeephram

2022-08-18 05:11 UTC, sharanyab16 commented
Jenkins please retry a build

2022-08-18 12:50 UTC, sharanyab16 commented
Jenkins please retry a build

2022-08-23 04:57 UTC, gvarao requested changes

2022-08-23 04:57 UTC, gvarao commented on community_supplied/Subscriber-Service/service.aaa-monitor-radius-server-delay.rule
> +                    frequency 30s;
See if frequency can be changed to 60s in all rules. It is just recommendation by keeping performance in mind

2022-08-23 04:57 UTC, gvarao commented on community_supplied/Subscriber-Service/service.dhcp-relay-monitor-dhcpv4-server-delay.rule
> +                    frequency 30s;
Same comment as previous rule

2022-08-23 06:08 UTC, gvarao approved these changes

2022-08-23 06:08 UTC, merged