RE-Rule-Trigger-Update
Juniper/healthbot-rules pull request #698
Opened 2023-01-30 13:10 UTC by vvikramb

For the rule "hardware.chassis/check-routing-engine-temperature", the trigger conditions for RE temperature and RE CPU temperature are modified to match the below condition.
•	If value is less than high threshold display is green.
•	If value is less than critical threshold display is yellow.
•	If value is greater than or equal to high threshold display is yellow.
•	If value is greater than or equal to critical threshold display is red.

2023-02-01 02:41 UTC, gaddevijay requested changes

2023-02-01 02:41 UTC, gaddevijay commented on juniper_official/chassis/check-routing-engine-temperature.rule
> +                            message "$routing-engine temperature($routing-engine-temperature degree C) exceeds low threshold";
Are we still calling this as low threshold in the message? I thought we were calling it high or critical based on what is represented in UI graphs

2023-02-01 04:12 UTC, vvikramb commented on juniper_official/chassis/check-routing-engine-temperature.rule
> +                            message "$routing-engine temperature($routing-engine-temperature degree C) exceeds low threshold";
Updated trigger messages from low/high threshold to high/critical thresholds.

2023-02-02 04:35 UTC, gaddevijay approved these changes

2023-02-02 04:35 UTC, merged