COL-190: Traffic Blackhole Inference:Traffic blackhole Integration to OC-term and GNMI-term- Validation
Juniper/healthbot-rules pull request #787
Opened 2023-03-30 05:52 UTC by skk-JNPR

Adding missing rules and files for Traffic Blackhole

2023-04-18 15:50 UTC, swamysrk approved these changes
Looks good. For ACX testing, we may have update all the traffic blackhole rules to include ACX platforms.

2023-04-18 15:51 UTC, swamysrk approved these changes

2023-04-18 15:51 UTC, swamysrk approved these changes

2023-04-18 15:54 UTC, swamysrk approved these changes

2023-04-24 08:38 UTC, gvarao requested changes

2023-04-24 08:38 UTC, gvarao commented on juniper_official/Solutions/Traffic-Blackhole/npu-resources.rule
> +			synopsis "PFE Hardware Resource";
Please have more specific synopsis

2023-04-24 08:38 UTC, gvarao commented on juniper_official/Solutions/Traffic-Blackhole/npu-resources.rule
> +						                platforms All {
I hope you have qualified the rule on all ACK models. If not mention only tested models.

2023-04-25 08:45 UTC, merged