Modified Chassis sensor path
Juniper/healthbot-rules pull request #803
Opened 2023-04-16 04:51 UTC by vvikramb

Modified Chassis Sensor Path for "check-system-power-usage-temp-state" rule.

2023-04-18 06:44 UTC, gaddevijay requested changes

2023-04-18 06:44 UTC, gaddevijay commented on juniper_official/chassis/check-system-power-usage-temp-state.rule
> +                value 0-1;
Why is it restricted to only 0 and 1? Can we broaden the search?

2023-04-19 07:38 UTC, vvikramb commented on juniper_official/chassis/check-system-power-usage-temp-state.rule
> +                value 0-1;
Updated slot to (0-9).

2023-04-19 08:10 UTC, gaddevijay approved these changes

2023-04-19 08:10 UTC, merged