Added BFD rules
Juniper/healthbot-rules pull request #849
Opened 2023-11-30 16:20 UTC by gvarao

2023-12-07 16:33 UTC, gaddevijay requested changes

2023-12-07 16:33 UTC, gaddevijay commented on juniper_official/routing/bfd-session-state.rule
> +                    frequency 60s;
3min

2023-12-07 16:33 UTC, gaddevijay commented on juniper_official/routing/bfd-session-state.rule
> +                frequency 1.5offset;
1 offset

2023-12-07 16:33 UTC, gaddevijay commented on juniper_official/routing/bfd-session-state.yml
> +        remote-state: remote-state
scale? and xslt

2023-12-08 10:25 UTC, gvarao commented on juniper_official/routing/bfd-session-state.rule
> +                    frequency 60s;
Increased to 180Sec

2023-12-08 10:25 UTC, gvarao commented on juniper_official/routing/bfd-session-state.rule
> +                frequency 1.5offset;
Modified

2023-12-08 10:26 UTC, gvarao commented on juniper_official/routing/bfd-session-state.yml
> +        remote-state: remote-state
It will be addressed in FH-2810

2023-12-10 13:11 UTC, gaddevijay requested changes

2023-12-10 13:11 UTC, gaddevijay commented on juniper_official/routing/bfd-session-state.rule
> +                        operating-system junos {
What about EVO and and ACX?

2023-12-11 05:45 UTC, gvarao commented on juniper_official/routing/bfd-session-state.rule
> +                        operating-system junos {
Added EVO and ACX in meta data

2023-12-12 02:24 UTC, gaddevijay requested changes

2023-12-12 02:24 UTC, gaddevijay commented on juniper_official/routing/bfd-session-state.rule
> +                        operating-system junosEvolved {
there should be one for vmx as well

2023-12-12 02:26 UTC, gaddevijay requested changes

2023-12-12 02:26 UTC, gaddevijay commented on juniper_official/routing/bfd-session-state.rule
> +                                platforms All {
there is nothing like platforms ALL, this was a mistake in older rules, either mention each of the products or put a default sensor at platform level

2023-12-12 04:13 UTC, gvarao commented on juniper_official/routing/bfd-session-state.rule
> +                        operating-system junosEvolved {
VMX will be added after qualification

2023-12-13 02:39 UTC, gaddevijay approved these changes

2023-12-13 02:39 UTC, merged