Updated no-errors term in ospf-io-stats rule
Juniper/healthbot-rules pull request #853
Opened 2023-12-12 08:52 UTC by vvikramb

Updated no-errors term in "routing.ospf/check-ospf-io-statistics" rule.

2023-12-12 15:01 UTC, gaddevijay requested changes

2023-12-12 15:01 UTC, gaddevijay commented on juniper_official/routing/check-ospf-io-statistics.rule
> +                            products PTX {
what about vmx?

2023-12-13 02:22 UTC, vvikramb commented on juniper_official/routing/check-ospf-io-statistics.rule
> +                            products PTX {
Added for VMX.

2023-12-13 05:09 UTC, gaddevijay approved these changes

2023-12-13 05:09 UTC, merged